name: ghcr publish

on:
  push:
    branches: ["dev", "main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-dev:
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/dev')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache node packages
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: npm install and npm run CI commands
        run: |
          npm ci
          npm run build:ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,prefix=,format=long
            type=raw,value=dev,enable=${{ github.ref == format('refs/heads/{0}', 'dev') }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-dev:
    needs: build-and-push-dev
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone GitOps repo
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_PUSH_TOKEN }}@github.com/techgardencode/homelab.git
          cd homelab/kubernetes/clusters
          echo "GITOPS_BASE_PATH=$PWD" >> $GITHUB_ENV

      - name: Update kustomization.yaml with new image tag
        run: |
          cd $GITOPS_BASE_PATH
          yq -i '.image.tag = "${{ github.sha }}"' 1276-dev/techgarden/www/values.yaml

      - name: Commit and push to GitOps repo
        run: |
          cd $GITOPS_BASE_PATH
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add 1276-dev/techgarden/www/values.yaml
          git commit -m "chore: update tag to ${{ github.sha }}"
          git push
